# Generated by Django 5.0.6 on 2024-05-23 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0004_rename_descriotion_project_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='image',
            field=models.ImageField(default='default', upload_to='portfolio/images/'),
            preserve_default=False,
        ),
    ]
