# Generated by Django 5.0.6 on 2024-05-23 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0005_project_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='image',
            field=models.ImageField(default='portfolio/images/', upload_to='portfolio/images/'),
        ),
    ]
